version: '3.8'

services:
  db:
    container_name: postgis
    image: postgis/postgis:13-3.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./database/data/postgis:/var/lib/postgresql/data
      - ./database/scripts/create.sql:/docker-entrypoint-initdb.d/init.sql postgres_data